export const testIds = {
  app: {
    navChat: 'nav-chat',
    navStudio: 'nav-studio',
    navChannels: 'nav-channels',
    navMcp: 'nav-mcp',
    logout: 'app-logout',
    authStateRetry: 'app-auth-state-retry',
    setupStateRetry: 'app-setup-state-retry',
  },
  auth: {
    username: 'auth-username',
    password: 'auth-password',
    confirmPassword: 'auth-confirm-password',
    submit: 'auth-submit',
  },
  setup: {
    stepProvider: 'setup-step-provider',
    stepChannel: 'setup-step-channel',
    stepAgent: 'setup-step-agent',
    providerSelect: 'setup-provider-select',
    modelInput: 'setup-model-input',
    apiKeyInput: 'setup-api-key-input',
    apiBaseInput: 'setup-api-base-input',
    providerSubmit: 'setup-provider-submit',
    channelMode: 'setup-channel-mode',
    channelSubmit: 'setup-channel-submit',
    workspaceInput: 'setup-workspace-input',
    agentSubmit: 'setup-agent-submit',
  },
  profile: {
    username: 'profile-username',
    displayName: 'profile-display-name',
    email: 'profile-email',
    saveProfile: 'profile-save',
    currentPassword: 'profile-current-password',
    newPassword: 'profile-new-password',
    confirmPassword: 'profile-confirm-password',
    rotatePassword: 'profile-rotate-password',
  },
  chat: {
    newSession: 'chat-new-session',
    sessionSearch: 'chat-session-search',
    composer: 'chat-composer',
    bubbleList: 'chat-bubble-list',
    fileInput: 'chat-file-input',
    uploadFile: 'chat-upload-file',
  },
  channels: {
    detailLinkPrefix: 'channels-detail-link-',
    deliverySave: 'channels-delivery-save',
    detailSave: 'channels-detail-save',
    detailTest: 'channels-detail-test',
    whatsappBindStart: 'channels-whatsapp-bind-start',
    whatsappBindStop: 'channels-whatsapp-bind-stop',
    whatsappBindRefresh: 'channels-whatsapp-bind-refresh',
  },
  mcp: {
    repoSource: 'mcp-repo-source',
    inspect: 'mcp-inspect',
    install: 'mcp-install',
    detailLinkPrefix: 'mcp-detail-link-',
    probePrefix: 'mcp-probe-',
    togglePrefix: 'mcp-toggle-',
    detailDisplayName: 'mcp-detail-display-name',
    detailEnv: 'mcp-detail-env',
    detailSave: 'mcp-detail-save',
    detailProbe: 'mcp-detail-probe',
    detailToggle: 'mcp-detail-toggle',
    detailTestInput: 'mcp-detail-test-input',
    detailTestSend: 'mcp-detail-test-send',
  },
} as const
